name: electron
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '* 0 * * *'

jobs:
  electron: # FIXME? takes 8min+
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.X'
      - name: ls
        run: ls

      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm install

      - name: electron-forge make
        run: npm run make
# FIXME
#     - name: out.zip
#       uses: actions/upload-artifact@v3
#       with:
#         name: out
#         path: out
